linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - misspell
    - goconst
    - revive
    - errcheck
    - unconvert
    - staticcheck
    - varcheck
    - structcheck
    - deadcode
    - unused
    - stylecheck
    - gosimple
    - goimports
issues:
  exclude-rules:
    - path: sdk/types
      linters:
        - revive
    - path: sdk/sys
      linters:
        - revive
    - path: pkg/constants
      linters:
        - errcheck
    - path: pkg/specactors
      linters:
        - errcheck
  exclude-use-default: false
linters-settings:
  goconst:
    min-occurrences: 6
run:
  skip-dirs-use-default: false
  skip-dirs: "(testing)"
  skip-files: "(.*_gen\\.go$)"
