// Code generated by github.com/ipfs-force-community/go-fvm-sdk. DO NOT EDIT.
package client

import (
	"bytes"
	context "context"
	"fmt"

	address "github.com/filecoin-project/go-address"
	abi "github.com/filecoin-project/go-state-types/abi"
	"github.com/filecoin-project/go-state-types/big"
	builtin "github.com/filecoin-project/go-state-types/builtin"
	init8 "github.com/filecoin-project/specs-actors/v8/actors/builtin/init"
	actors "github.com/filecoin-project/venus/venus-shared/actors"
	types "github.com/filecoin-project/venus/venus-shared/types"
	sdkTypes "github.com/ipfs-force-community/go-fvm-sdk/sdk/types"
	cid "github.com/ipfs/go-cid"

	v0 "github.com/filecoin-project/venus/venus-shared/api/chain/v0"
)

type FullNode interface {
	MpoolPushMessage(ctx context.Context, msg *types.Message, spec *types.MessageSendSpec) (*types.SignedMessage, error)
	StateWaitMsg(ctx context.Context, cid cid.Cid, confidence uint64) (*types.MsgLookup, error)
}

type IStateClient interface {
	Install(context.Context, []byte, ...SendOption) (*sdkTypes.InstallReturn, error)

	CreateActor(context.Context, cid.Cid, ...SendOption) (*init8.ExecReturn, error)

	SayHello(context.Context, ...SendOption) (sdkTypes.CBORBytes, error)
}

var _ IStateClient = (*StateClient)(nil)

type StateClient struct {
	node v0.FullNode
	cfg  ClientOption
}

// Option option func
type Option func(opt *ClientOption)
type SendOption func(opt *ClientOption)

// ClientOption option for set client config
type ClientOption struct {
	fromAddress address.Address
	actor       address.Address
	codeCid     cid.Cid
}

// SetFromAddressOpt used to set from address who send actor messages
func SetFromAddressOpt(fromAddress address.Address) Option {
	return func(opt *ClientOption) {
		opt.fromAddress = fromAddress
	}
}

// SetFromAddrSendOpt used to set from address who send actor messages
func SetFromAddrSendOpt(fromAddress address.Address) SendOption {
	return func(opt *ClientOption) {
		opt.fromAddress = fromAddress
	}
}

// SetActorOpt used to set actor address
func SetActorOpt(actor address.Address) Option {
	return func(opt *ClientOption) {
		opt.actor = actor
	}
}

// SetCodeCid used to set actor code cid
func SetCodeCid(codeCid cid.Cid) Option {
	return func(opt *ClientOption) {
		opt.codeCid = codeCid
	}
}

func NewStateClient(fullNode v0.FullNode, opts ...Option) *StateClient {
	cfg := ClientOption{}
	for _, opt := range opts {
		opt(&cfg)
	}
	return &StateClient{
		node: fullNode,
		cfg:  cfg,
	}
}

func (c *StateClient) ChangeFromAddress(addr address.Address) {
	c.cfg.fromAddress = addr
}

func (c *StateClient) Install(ctx context.Context, code []byte, opts ...SendOption) (*sdkTypes.InstallReturn, error) {
	cfg_copy := c.cfg
	for _, opt := range opts {
		opt(&cfg_copy)
	}
	params, aerr := actors.SerializeParams(&sdkTypes.InstallParams{
		Code: code,
	})
	if aerr != nil {
		return nil, fmt.Errorf("failed to serialize params: %w", aerr)
	}

	msg := &types.Message{
		To:     builtin.InitActorAddr,
		From:   cfg_copy.fromAddress,
		Value:  big.Zero(),
		Method: 4,
		Params: params,
	}

	smsg, err := c.node.MpoolPushMessage(ctx, msg, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to push message: %w", err)
	}

	wait, err := c.node.StateWaitMsg(ctx, smsg.Cid(), 0)
	if err != nil {
		return nil, fmt.Errorf("error waiting for message: %w", err)
	}

	// check it executed successfully
	if wait.Receipt.ExitCode != 0 {
		return nil, fmt.Errorf("actor installation failed")
	}

	var result sdkTypes.InstallReturn
	r := bytes.NewReader(wait.Receipt.Return)
	if err := result.UnmarshalCBOR(r); err != nil {
		return nil, fmt.Errorf("error unmarshaling return value: %w", err)
	}
	c.cfg.codeCid = result.CodeCid
	return &result, nil
}
func (c *StateClient) CreateActor(ctx context.Context, codeCid cid.Cid, opts ...SendOption) (*init8.ExecReturn, error) {
	cfg_copy := c.cfg
	for _, opt := range opts {
		opt(&cfg_copy)
	}

	params, aErr := actors.SerializeParams(&init8.ExecParams{
		CodeCID: codeCid,
	})

	if aErr != nil {
		return nil, fmt.Errorf("failed to serialize params: %w", aErr)
	}

	msg := &types.Message{
		To:     builtin.InitActorAddr,
		From:   cfg_copy.fromAddress,
		Value:  big.Zero(),
		Method: 2,
		Params: params,
	}

	smsg, err := c.node.MpoolPushMessage(ctx, msg, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to push message: %w", err)
	}

	wait, err := c.node.StateWaitMsg(ctx, smsg.Cid(), 0)
	if err != nil {
		return nil, fmt.Errorf("error waiting for message: %w", err)
	}

	// check it executed successfully
	if wait.Receipt.ExitCode != 0 {
		return nil, fmt.Errorf("actor execution failed")
	}

	var result init8.ExecReturn
	r := bytes.NewReader(wait.Receipt.Return)
	if err := result.UnmarshalCBOR(r); err != nil {
		return nil, fmt.Errorf("error unmarshaling return value: %w", err)
	}
	c.cfg.actor = result.IDAddress
	return &result, nil
}

func (c *StateClient) SayHello(ctx context.Context, opts ...SendOption) (sdkTypes.CBORBytes, error) {
	cfg_copy := c.cfg
	for _, opt := range opts {
		opt(&cfg_copy)
	}
	if c.cfg.actor == address.Undef {
		return nil, fmt.Errorf("unset actor address for call")
	}

	msg := &types.Message{
		To:     cfg_copy.actor,
		From:   cfg_copy.fromAddress,
		Value:  big.Zero(),
		Method: abi.MethodNum(0xc551429c),
		Params: nil,
	}

	smsg, err := c.node.MpoolPushMessage(ctx, msg, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to push message: %w", err)
	}

	wait, err := c.node.StateWaitMsg(ctx, smsg.Cid(), 0)
	if err != nil {
		return nil, fmt.Errorf("error waiting for message: %w", err)
	}

	// check it executed successfully
	if wait.Receipt.ExitCode != 0 {
		return nil, fmt.Errorf("actor execution failed")
	}
	if len(wait.Receipt.Return) == 0 {
		return nil, fmt.Errorf("expect get result for call")
	}

	result := new(sdkTypes.CBORBytes)
	result.UnmarshalCBOR(bytes.NewReader(wait.Receipt.Return))

	return *result, nil

}
